### ISSUE TITLE
Not extracting all resources.

### ISSUE THREAD

**Issue by amundskm** [AoE2CommunityGitHub/WololoKingdoms#1]
After downloading the latest release. I could not get the installer to work. It was deleting files out of the resources folder. I know it is deleting SetupAoc.exe, and there are others, but I didn't catch what they were.  It happens around 75% completion.

error message: boost::filesystem::copy_file: The system cannot find the file specified: "resources\SetupAoc.exe", "C:\Program Files\microsoft games\age of empires ii\SetupAoc.exe"

Windows defender saw SetupAoc.exe as a virus. So it removed it without telling me or permission? I turned off windows defender and everything worked fine.

**Comment by meichthys** [comment]
^ This was also the case for me. Disabling windows defender temporarily during installation worked for me too.

**Comment by Cyphierion** [comment]
Windows 10 isn't very nice - Turn off all Antivirus Programs and as well as Windows 10 Defender/Anti-Virus
