### ISSUE TITLE
Feature request: Split a portable library off from the main code base

### ISSUE THREAD

**Issue by hhirsch** [AoE2CommunityGitHub/WololoKingdoms#13]
If a portable library was separate from the OS dependent code (windows.h) it could be used to write cli-tools for mac and linux that can be used to get the job done without the risk of the UI not running in wine.

**Comment by Jineapple** [comment]
This should be resolved before work on other issues is done, to avoid implementing things twice. If there's someone to help with testing and finalising the build process on windows, that would be great.
