### ISSUE TITLE
downloadlinks are invalid

### ISSUE THREAD

**Issue by bgstack15** [AoE2CommunityGitHub/WololoKingdoms#14]
Against release [5.8.1](https://github.com/AoE2CommunityGitHub/WololoKingdoms/releases/download/5.8.1/WololoKingdoms.5.8.1.zip): the downloadlinks.txt contents point to downloads that are behind authentication. These cannot be downloaded correctly and it keeps causing the WololoKingdoms Updater to crash.

**Comment by Jineapple** [comment]
Thanks, this has been fixed in the new updater
