### ISSUE TITLE
updater is not working

### ISSUE THREAD

**Issue by julianeden** [AoE2CommunityGitHub/WololoKingdoms#15]
for myself as well as many others (f1re / miguel / riut / goku reported same issue), the installer just stops and crashes when run. it says "downloading..." then says "installing..." then crashes.

i am running win7, idk about the others. i doubt it's just us.

my steam version of aoe is fully updated.

**Comment by akhilkedia** [comment]
Me and 3 others I know also had this issue.
For me, the installer had the buttons greyed out as well.
I'm on windows 10. Steam version fully updated.

**Solution**
Disabling anti-virus worked for one person.
Downloading `5.7.4` release from the releases page on github and running the `WKupdater.exe` there worked for me. It downloaded something, then started the installer for `5.8.1`.
