### ISSUE TITLE
Updater can't find my games

### ISSUE THREAD

**Issue by Malakhor** [AoE2CommunityGitHub/WololoKingdoms#30]
I've downloaded the latest update but everytime I start it, it says that it can't find my AoE games. I have placed the Wololokingdoms folder in my AoE 2 HD folder but it still can't find it. I've read through the readme file but can't find a solution.
What should I do? Any ideas?

**Comment by gregstein** [comment]
Hello,

Could you take a screenshot of that error?

**Comment by Malakhor** [comment]
![Printscreen 1](https://user-images.githubusercontent.com/50081977/57275972-63071e80-70a0-11e9-8888-268f0997f98a.png)
![Printscreen 2](https://user-images.githubusercontent.com/50081977/57275974-639fb500-70a0-11e9-8edf-10907a3dd8e8.png)

**Comment by Jineapple** [comment]
You need to have a working installation of AoC first before the WK installer can function. Aoe2Tools is a good option to get that. Then you can either use the WK option shipped with aoe2tools or run the regular WK installer.
