### ISSUE TITLE
Graphics Bug - No Military Units

### ISSUE THREAD

**Issue by SupaNub** [AoE2CommunityGitHub/WololoKingdoms#33]
I am having issues with the WololoKingdoms mod,

While running Aoe2 through voobly without WololoKingdoms the game works fine,
However when I use the WololoKingdoms Mod the graphics start to bug out,
While villagers and my buildings seem to render correctly, military units and enemy buildings are invisible and unable to be selected.
Additionally the UI bar at the bottom of the screen fills the screen solitaire style on occasion.

Any tips or fixes? I can't seem to find the issue anywhere,

**Comment by Jineapple** [comment]
1. Make sure there's no "compatslp" folder in your Age2HD directory. If it's there, delete it (normally the installer should take care of this, but make sure anyway)
2. Verify your game files on HD
3. Make sure your installer is updated (Current version is 5.8.1 (e) )
3. Do a reinstallation. If that alone doesn't solve it, first remove any folder under /Voobly Mods/AoC/Data Mods as well as /Games that have WololoKingdoms or WK in their name (back up any rec games, maps etc. you might have in there), then reinstall again. 

Such a clean reinstall should normally take care of any issues like that.

**Comment by SupaNub** [comment]
I had done this in the past, however apparently one more time was necessary haha,

All working now,
