### ISSUE TITLE
Installer not working (visual glitches, run button disabled)

### ISSUE THREAD

**Issue by Thewolfs** [AoE2CommunityGitHub/WololoKingdoms#4]
Hi,

I've tried installing WoloKingdoms with Vooble but I can't seem to make the installer to work. Am I missing something ? I've downloaded it twice and tried copying the folder in Ao2 directory but nothing changed

Here's a screenshot

![image](https://user-images.githubusercontent.com/10207906/42286407-0d97c294-7fb3-11e8-93b8-15cf5ae81cfb.png)

Thanks in advance for your help

**Comment by Jineapple** [comment]
Two things:
1. It looks like some files weren't able to load properly (no icons on the info buttons, empty data mod list). Make sure your antivirus isn't deleting/quarantining files for some reason (Temporarily disable it/possibly redownload files)
2. There is no install directory set. Normally this should happen automatically. If it doesn't, try doing it yourself. Select your AoC installation directory which has an age2_x1 folder in it (If using the steam version with compatibility patch, that's the Age2HD folder)

**Comment by Jineapple** [comment]
Well, normally that window would give you an error message, but it's missing the language file with that message.

Missing files would be (at least) resources/question.png and possibly resources/en.txt.

Please try the following: 
1. Temporarily disable your antivirus
2. Redownload the installer, unpack it from the zip
3. Run it again. this time all the required files should hopefully be there.

**Comment by Thewolfs** [comment]
I redownloaded it with my antivirus off and Windows Defender is also off and sadly it didn't change anything

I looked for the files and they are there, so I don't get why the aren't getting loaded properly ...

When I click on the button to look for my install it doesn't do anything. Not sure why

**Comment by rusty-electron** [comment]
I am having the same issue with the installer.

**Comment by javiersegovia** [comment]
I have the same issue. Anyone got a fix?

**Comment by barnaba** [comment]
Exactly the same issue, but I'm on wine.

**Comment by Jineapple** [comment]
Okay, I've had some time to look at this. The error you're getting is due to an Age2HD installation not being detected. At that point in the program, the language strings haven't been loaded yet, which is why the error message was blank. This I fixed. Can you confirm that you have Age2HD installed correctly?

**Comment by barnaba** [comment]
Sorry, I wasn't clear in my previous message. I had no steam running and no Age2HD installed - since it's hard to get any good info about wine compatibility I wanted to check if the WK converter runs at all on wine first (even before buying the game, cause honestly it's useless for me without your project).

So in my case the 5.7 error was the correct behavior and I imagine your fix will work. Can't speak for the others though.

**Comment by Cyphierion** [comment]
SOLUTION! - For Age of Empires 2 and Content Stuffs
~ You MUST have AoK+TC from the CD Version installed!!!
~ You MUST have Age of Empires 2 HD Edition on Steam and also installed!!!

![image](https://user-images.githubusercontent.com/35496928/43420238-2d3c6d58-9411-11e8-93f6-cbdfc99e0bf3.png)

Copy all files from the left to the right... (Yes, Merging the contents of the left folder with the contents with the right folder)... Overwrite ALL Conflicts. Run the "WololoKingdoms.exe" program... Set up your settings and viola! Good to go! ~ Run WK.exe in the age2_x1 folder!

**Comment by Jineapple** [comment]
Okay, looks like this is just an issue with either Steam not running or HD not being installed, but the error message wasn't shown properly. Will be fixed with the next update for 5.8. Closing this now
