### ISSUE TITLE
Run button can be cut off

### ISSUE THREAD

**Issue by Jineapple** [AoE2CommunityGitHub/WololoKingdoms#48]
If a monitor has a small resolution or high scaling, it's possible the installer window becomes too high to fit fully on the screen, cutting of the run button.

**Comment by gregstein** [comment]
Hello,

I hope you're doing well friend. I'm not a c++ developer but surely you need to use anchoring on your button so it remains intact. 
Some random solution: https://stackoverflow.com/questions/3672921/how-to-anchor-pushbutton-to-the-widget
