### ISSUE TITLE
Flags are not positioned correctly on buildings with garrisoned units

### ISSUE THREAD

**Issue by hhirsch** [AoE2CommunityGitHub/WololoKingdoms#5]

**Comment by Jineapple** [comment]
There is a checkbox for "adjust garrison flags". If you use the WK architecture showcase mod on voobly, you should check it, it shifts the flags for the new models. If you use the default architecture, make sure this box is unchecked.

**Comment by hhirsch** [comment]
I ran some tests and these are the results.
![briton-castle-original](https://user-images.githubusercontent.com/2451426/42417367-58eda45c-8288-11e8-9a93-7c939d93839b.png)
Briton Castle with the WK flag option enabled and the showcase mod disabled
![briton-castle](https://user-images.githubusercontent.com/2451426/42417379-d42b65e6-8288-11e8-915f-c84b84cc254d.png)
Briton Castle with the WK flag option enabled and the showcase mod enabled
![berber-castle](https://user-images.githubusercontent.com/2451426/42417369-59248170-8288-11e8-8986-9752043b8c0a.png)
Berber Castle with the WK flag option enabled and the showcase mod enabled

**Comment by Jineapple** [comment]
The first two are as expected. For the Berber Castle, I think that one is a new addition to the showcase mod and the Flags adjustment file hasn't been updated.

@TriRem / @AoE2CommunityGitHub  is that something you could look into? Needs to be added to the WKFlags.txt file. Format should be: Civ ID, Unit ID,Delta Index of the flag in the garrison graphics, new x coordinate, new y coordinate.

Would need two lines for the two flags.

**Comment by Jineapple** [comment]
Should be fixed in 5.8.1
