### ISSUE TITLE
Vertical Resolutions lower than 768 break the UI

### ISSUE THREAD

**Issue by StormyStrife** [AoE2CommunityGitHub/WololoKingdoms#50]
I get this UI bug. I typically use 1280x720 resolution, except the problem also happens with 800x600 as well.

Changing the resolution does literally nothing. I'm playing as Khmer in this screenshot. If I go to a resolution above 720, say, 768 or 800, then the UI totally changes to the real one and it works. I don't have this problem in the HD edition though, only Voobly when I use this mod.
![unknown](https://user-images.githubusercontent.com/57286499/68069363-8f80b800-fd1c-11e9-92e1-f4e491c2798a.png)

I can play with this UI, but realistically it's not easy. I can't really go to a higher resolution mostly because I play windowed. I stream and OBS is a bit dumb sometimes, so windowed is the best way to go for me. IN a larger resolution, the game window is cut off by the taskbar. I could move it, but I'm kinda lazy, and this is also the only game I have this problem with anyways.

**Comment by gregstein** [comment]
Did you try to download those files into mod_rewrite folder, then reinstall as jine suggested?

**Comment by StormyStrife** [comment]
Yeah, I didn't think it would work, but it did. Ooops, sorry about that.
