### ISSUE TITLE
Issue with siege tower

### ISSUE THREAD

**Issue by Jineapple** [AoE2CommunityGitHub/WololoKingdoms#52]
https://www.voobly.com/forum/thread/312860/:1358041

There seems to be an issue with the siege tower in newer versions of 5.8.1. I suspect this may be due  to compression issues / the way the .dat is saved.

**Comment by goto-bus-stop** [comment]
was this fixed by the copied ID fix in #49?

**Comment by Jineapple** [comment]
It was unrelated to the copied IDs but still fixed, simply a case of the wrong attribute being set. That happened with the renaming of attributes in the newer genieutils version.
